### ISSUE TITLE
LInks for downloading checkpoint and mat file not working 

### ISSUE THREAD

**Issue by cgarg-tud** [Lilyo/DEN#1]
Hi, 

Thankyou for your work. I wanted to use the pre-computed depth maps of scannet dataset as baseline for evaluation. But the link for downloading 650291.mat is not working and is same as checkpoint link.

**Comment by Lilyo** [comment]
@cgarg-tud I am sorry for the missing URL! I will upload it as soon as possible, thank you for your report.

**Comment by Lilyo** [comment]
@cgarg-tud Link has been updated!
